# Auth0 Client Configuration (app-oidc)
auth0_client:
  name: "Application - Acceptance Test"
  app_type: "spa"
  is_first_party: true
  oidc_conformant: true
  callbacks:
    - "https://example.com/callback"
  
  grant_types:
    - "authorization_code"
    - "refresh_token"
  
  jwt_configuration:
    lifetime_in_seconds: 300
    secret_encoded: true
    alg: "RS256"
  
  refresh_token:
    rotation_type: "rotating"
    expiration_type: "expiring"