# ========================================
# AUTH0 POLICY REQUIREMENTS (auth0.policy)
# ========================================

# Valid app_type (only regular_web and spa allowed)
app_type: "regular_web"

# Valid grant_types (no password grant)
grant_types:
  - "authorization_code"
  - "refresh_token"

# Valid MFA factors (no email or sms)
mfa_factors:
  - "otp"
  - "webauthn-roaming"

# Valid token lifetime (< 600 seconds)
id_token_lifetime: 300

# Valid scopes
scopes:
  - "openid"
  - "profile"
  - "email"
  - "offline_access"

# Refresh token rotation enabled (recommended for regular_web + offline_access)
refresh_token_rotation_enabled: true

# ================================================
# SHARED-SEC POLICY REQUIREMENTS (shared_sec.rego)
# ================================================

# Password policy meeting baseline requirements
passwordPolicy:
  length:
    min: 16           # Must be >= 16 (from identity_access.yml)
  history: 10         # Must be >= 10 (from identity_access.yml)

# Guardian MFA policy meeting baseline requirements  
guardianMfaPolicy:
  factors:
    - name: "otp"
      enabled: true   # Required by policy
    - name: "webauthn-roaming"
      enabled: true   # Required by policy  
    - name: "sms"
      enabled: false  # Must be disabled by policy

# ========================================
# ADDITIONAL VALID AUTH0 CONFIGURATION
# ========================================

# Other valid Auth0 settings
client_id: "test-client-123"
client_secret: "test-secret-456"

callbacks:
  - "https://myapp.com/callback"
  - "https://myapp-staging.com/callback"

logout_urls:
  - "https://myapp.com/logout"
  - "https://myapp-staging.com/logout"

web_origins:
  - "https://myapp.com"
  - "https://myapp-staging.com"

# Additional security settings
token_endpoint_auth_method: "client_secret_post"
