# Environment metadata (for your tooling)
env: dev
tenant: tenantA

# Auth0 branding configuration
branding:
  colors:
    primary: "#228BE6"  # dev-blue

# Tenant session settings (dev is more relaxed)
tenant:
  session_lifetime: 7200        # 120 minutes = 7200 seconds
  idle_session_lifetime: 259200 # 72 hours = 259200 seconds

# Token settings for applications
clients:
  - name: "default-app"
    jwt_configuration:
      lifetime_in_seconds: 7200  # 2 hours access token
    refresh_token:
      expiration_type: "expiring"
      lifetime_in_seconds: 2592000  # 30 days