# Environment metadata
env: prod
tenant: tenantA

# Auth0 branding configuration
branding:
  colors:
    primary: "#0CA678"  # prod-green

# Tenant session settings (prod is stricter)
tenant:
  session_lifetime: 1200   # 20 minutes = 1200 seconds
  idle_session_lifetime: 43200  # 12 hours = 43200 seconds

# Token settings (prod tightens TTLs)
clients:
  - name: "default-app"
    jwt_configuration:
      lifetime_in_seconds: 1800  # 30 minutes access token
    refresh_token:
      expiration_type: "expiring"
      lifetime_in_seconds: 1209600  # 14 days