# Baseline security configuration for all Auth0 tenants

identity_access:
  password_policy:
    strength: "good"
    min_length: 12
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special: true
    history:
      enabled: true
      size: 5
    max_age_days: 90

mfa:
  policy: "all-applications"
  factors:
    sms: false
    push: true
    otp: true
    webauthn: true

session:
  idle_timeout_minutes: 30
  absolute_timeout_hours: 8

branding:
  logo_url: "https://ciam.example.com/logo.png"
  primary_color: "#0057b8"
  page_background: "#ffffff"
  font_url: "https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap"
  universal_login:
    default_theme: "corporate"

universal_login:
  experience: "new"
  identifier_first: true

connections:
  database:
    name: "CUstom-Username-Password-Authentication"
    enabled: true