# config.yml - Sample Auth0 Client Configuration

client:
  name: "Sample App-test-pr"
  app_type: "spa"
  description: "Sample application deployed via Terraform"
  
  callbacks:
    - "https://localhost:3000/callback"
    - "https://dev.example.com/callback"
  
  allowed_logout_urls:
    - "https://localhost:3000"
    - "https://dev.example.com"
  
  allowed_origins:
    - "https://localhost:3000"
    - "https://dev.example.com"
  
  allowed_web_origins:
    - "https://localhost:3000"
    - "https://dev.example.com"
  
  grant_types:
    - "authorization_code"
    - "refresh_token"
  
  token_endpoint_auth_method: "none"
  
  jwt_configuration:
    lifetime_in_seconds: 3600
    alg: "RS256"
  
  refresh_token:
    rotation_type: "rotating"
    expiration_type: "expiring"
    token_lifetime: 2592000  # 30 days
  
  cross_origin_auth: true
  oidc_conformant: true
  sso_disabled: false