connections:
  database:
    - name: "Username-Password-Authentication"
      password_policy: "excellent"
      password_complexity_options:
        min_length: 12
        require_uppercase: true
        require_lowercase: true
        require_numbers: true
        require_symbols: true
      brute_force_protection: true

guardian:
  enabled: true
  factors:
    - name: "otp"
      enabled: true
    - name: "sms"
      enabled: true

sessions:
  lifetime_in_hours: 4

tokens:
  access_token:
    lifetime_in_seconds: 900
  refresh_token:
    lifetime_in_seconds: 604800
    rotation_enabled: true

security:
  allowed_origins:
    - "https://app.example.com"

anomaly_detection:
  brute_force_protection:
    enabled: true
  breached_password_detection:
    enabled: true