application:
  name: "app2"
  app_type: "native"

grant_types:
  - "authorization_code"
  - "refresh_token"
  
response_types:
  - "code"
  
token_endpoint_auth_method: "none"  # Confidential client per security.yml
  
cross_origin_auth: false  # Required for regular_web per security.yaml
oidc_conformant: true  # Required per security.yaml
sso_disabled: false
  
allowed_web_origins:
  - "https://admin.mycompany.com"
  - "https://staging-admin.mycompany.com"
  - "http://localhost:8080"
