name: Validate Auth0 Secrets

on:
  workflow_dispatch:

jobs:
  validate-dev-secrets:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Get Auth0 Access Token
        id: get_token
        run: |
          TOKEN_RESPONSE=$(curl --silent --show-error --request POST \
            --url 'https://${{ secrets.DEV_AUTH0_DOMAIN }}/oauth/token' \
            --header 'content-type: application/json' \
            --data '{"client_id":"${{ secrets.DEV_AUTH0_CLIENT_ID }}","client_secret":"${{ secrets.DEV_AUTH0_CLIENT_SECRET }}","audience":"https://${{ secrets.DEV_AUTH0_DOMAIN }}/api/v2/","grant_type":"client_credentials"}'
          )

          if echo "$TOKEN_RESPONSE" | grep -q "access_token"; then
            echo "✅ Successfully retrieved an access token for the dev environment."
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "❌ Failed to retrieve a token. Check your secrets and domain."
            echo "status=failure" >> $GITHUB_OUTPUT
            exit 1
          fi
