name: Validate Auth0 Secrets
on:
  workflow_dispatch:
jobs:
  validate-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Get Auth0 Access Token
        run: |
          TOKEN_RESPONSE=$(curl --silent --show-error --request POST \
            --url 'https://${{ secrets.DEV_AUTH0_DOMAIN }}/oauth/token' \
            --header 'content-type: application/json' \
            --data '{"client_id":"${{ secrets.DEV_AUTH0_CLIENT_ID }}","client_secret":"${{ secrets.DEV_AUTH0_CLIENT_SECRET }}","audience":"https://${{ secrets.DEV_AUTH0_DOMAIN }}/api/v2/","grant_type":"client_credentials"}')
          if echo "$TOKEN_RESPONSE" | grep -q "access_token"; then
            echo "✅ dev: Token validation successful"
          else
            echo "❌ dev: Token validation failed"
            exit 1
          fi

  validate-qa:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Get Auth0 Access Token
        run: |
          TOKEN_RESPONSE=$(curl --silent --show-error --request POST \
            --url 'https://${{ secrets.QA_AUTH0_DOMAIN }}/oauth/token' \
            --header 'content-type: application/json' \
            --data '{"client_id":"${{ secrets.QA_AUTH0_CLIENT_ID }}","client_secret":"${{ secrets.QA_AUTH0_CLIENT_SECRET }}","audience":"https://${{ secrets.QA_AUTH0_DOMAIN }}/api/v2/","grant_type":"client_credentials"}')
          if echo "$TOKEN_RESPONSE" | grep -q "access_token"; then
            echo "✅ qa: Token validation successful"
          else
            echo "❌ qa: Token validation failed"
            exit 1
          fi
