name: Validate Auth0 Secrets
on:
  workflow_dispatch:
jobs:
  validate-secrets:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, qa, prod]
    environment: ${{ matrix.environment }}
    steps:
      - name: Get Auth0 Access Token
        run: |
          TOKEN_RESPONSE=$(curl --silent --show-error --request POST \
            --url 'https://${{ secrets.AUTH0_DOMAIN }}/oauth/token' \
            --header 'content-type: application/json' \
            --data '{"client_id":"${{ secrets.AUTH0_CLIENT_ID }}","client_secret":"${{ secrets.AUTH0_CLIENT_SECRET }}","audience":"https://${{ secrets.AUTH0_DOMAIN }}/api/v2/","grant_type":"client_credentials"}')
          if echo "$TOKEN_RESPONSE" | grep -q "access_token"; then
            echo "✅ ${{ matrix.environment }}: Token validation successful"
          else
            echo "❌ ${{ matrix.environment }}: Token validation failed"
            exit 1
          fi
